### PR TITLE
Enable depth buffer in case someone wants to use it

### PR DESCRIPTION
**Pull request by herbix**
I made this change because I want to use ModelBatch to render some real 3D model.

### CODE REVIEW

**Comment by kiooeht** [comment]
The depth buffer used to be enabled, but was disabled because it was causing crashes on Mac. See: [ce6772](https://github.com/daviscook477/BaseMod/commit/ce6772c0dd3e7d3706d6776ee06735d65957c49a)

**Comment by herbix** [comment]
@kiooeht 
Did you remember the error message?
It's surprising that it doesn't work on mac. Depth buffer is commonly used in 3d games.

**Comment by kiooeht** [comment]
Unfortunately there was no error message, the game would just close for the person having the issue and the log contained no errors. I spent a long time back and forth with the person testing different things, the framebuffers would get made, but the game would close immediately after.

Looking back on the conversation, they were using an M1 Mac (so likely an M1 Mac specific issue) and I narrowed it down to being a problem with the stencil buffer, so I'm not sure why I also disabled the depth buffer.

I'll check with them if they can test again and if enabling just the depth buffer still works.

**Comment by herbix** [comment]
Much appriciate. It would be good to have depth buffer at least.

**Pull request closed without merging**
