### PR TITLE
Add screen-space rendering postprocessor

### PR DESCRIPTION
**Pull request by herbix**
Modders can use this to make effects after whole screen has been rendered. The main reason for adding this is that if multiple mods use these patches, they are not compatible. Some effect may be overwrite by others.
Here's a sample screeenshot:
image

### CODE REVIEW

**Comment by herbix** [comment]
kiooeht, I saw your comment in discord channel.
Could you please hold this PR until I find a solution to make it compatible with mods that uses framebuffer?

**Comment by kiooeht** [comment]
I've already got a solution to that problem, plus a couple other minor improvements. No need for you to worry about fixing it.

**Comment by herbix** [comment]
That's awesome! 😄

**Comment by kiooeht** [comment]
I did that because it allows applying different affects to different "parts" of a frame by getting what has been rendered so far in a frame with this method I added and applying different shaders to that and the final frame in the post-processing step.
https://github.com/daviscook477/BaseMod/blob/20680b6584ed5997a36c6d1d9ab03ba8c2417a5c/mod/src/main/java/basemod/patches/com/megacrit/cardcrawl/core/CardCrawlGame/ApplyScreenPostProcessor.java#L35-L37

For example, it lets you do this, where the foreground UI has a different effect from the rest of the game.
java_o8T6XC4UZo
 
As for the overhead, I believe rendering to a framebuffer and then rendering that framebuffer to the screen should be a minuscule amount of overhead. A quick measuring of `BeforeSpriteBatchEnd` (with no post-processors) gave me the following timings. Each line is the total time `BeforeSpriteBatchEnd` took per ~1 second the game was running. Based on these numbers, the overhead of the framebuffer is about 1% of the total time each frame.
```
0.014s / 1.001814s
0.011s / 1.002104s
0.011s / 1.000244s
0.01s  / 1.000836s
0.019s / 1.003231s
0.012s / 1.002983s
0.01s  / 1.001171s
0.008s / 1.003784s
0.016s / 1.000373s
0.008s / 1.003472s
0.01s  / 1.002893s
0.014s / 1.002769s
0.012s / 1.003046s
0.009s / 1.000007s
```

For compatibility, it could be an issue, but I think it might be more confusing if there's compatibility issues only sometimes (i.e. when a post-processor is registered) that may not be noticed for a long time.

**Pull request merged**
